### ISSUE TITLE
[Bug] The config file cannot be save.

### ISSUE THREAD

**Issue by mcaruel** [graphlab-fr/cosma#41]
### Actions leading to the bug

I followed the following instruction from the user manual 
0. install cosma
1. create a directory `test`
2. create two subdirectories : `data` and `export`
3. run `cosma config` within the `test` directory

### Bug description

I get this message from the terminal:

```
/usr/local/lib/node_modules/@graphlab-fr/cosma/core/models/config.js:421
      throw new ErrorConfig('The config file cannot be save.');
      ^

Error Config: The config file cannot be save.
    at Config.save (/usr/local/lib/node_modules/@graphlab-fr/cosma/core/models/config.js:421:13)
    at module.exports (/usr/local/lib/node_modules/@graphlab-fr/cosma/controllers/config.js:10:90)
    at Command.<anonymous> (/usr/local/lib/node_modules/@graphlab-fr/cosma/app.js:56:40)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:488:17)
    at /usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:1050:25)
    at Command._parseCommand (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:1193:19)
    at Command.parse (/usr/local/lib/node_modules/@graphlab-fr/cosma/node_modules/commander/lib/command.js:897:10)

Node.js v18.16.0
```

### What version of Cosma are you using?

CLI 2.0-beta-1

### What is your operating system?

- [X] macOS
- [ ] Windows
- [ ] Linux

### What version of the operating system are you on?

13.4.1 (22F82)

**Comment by mcaruel** [comment]
Actually the file is created if using `sudo cosma config`. This is a bit strange since I have write credential for the directory `cosma-test`

**Comment by infologie** [comment]
Could you try updating to 2.0.0 and tell us if the problem persists?

**Comment by infologie** [comment]
Great!
